version: 0.2

phases:
  pre_build:
    commands:
      - echo Getting aws amplify default image
      - git clone https://github.com/aws-amplify/amplify-console.git
      - echo Logging in to Docker Hub...
      # Type the command to log in to your Docker Hub account here.          
      - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_TOKEN
  build:
    commands:
      - echo Build started on `date`
      - echo Building the original Docker image...   
      # this takes time. Could it be loaded from somewhere else instead of beeing built all the time?
      - docker build -t amplify-console/buildimage:latest ./amplify-console/images/latest/
      - echo Building the custom Docker image...   
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo Tagging the new custom Docker image...   
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the new Docker image to Docker Hub ...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG